baseURL = "https://haisholasur.github.io/portfoliokea/."
languageCode = "en-us"
publishDir = "docs"
title = "My New Hugo Site"
theme = "cocoa"

[[menu.main]]
name                   = "Home"
weight                 = -201
identifier             = "home"
url                    = "/"

[[menu.main]]
name                   = "Portfolio"
weight                 = -102
identifier             = "portfolio"
url                    = "/portfolio/"

[[menu.main]]
name                   = "Om"
weight                 = -103
identifier             = "om"
url                    = "/om/"


[[menu.main]]
name                   = "Blog"
weight                 = -101
identifier             = "blog"
url                    = "/blog/"
                   

[[menu.main]]
name                   = "Kontakt"
weight                 = -101
identifier             = "kontakt"
url                    = "/kontakt/"

                
